server:
  port: 8761

spring:
  application:
    name: discovery
  main:
    banner-mode: 'off'

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
